Adding Employee / Category Mappings
fylein/fyle-accounting-mappings pull request #32
Opened 2021-07-23 07:22 UTC by Shwetabhk

Adding new tables for employee and category mappings

2021-07-23 11:32 UTC, Shwetabhk commented
Payload of API
```json
{
    "source_employee": {
        "id": null
    },
    "destination_employee": {
        "id": null
    },
    "destination_vendor": {
        "id": null
    },
    "destination_card_account": {
        "id": null
    },
    "workspace": null
}
```

2021-07-23 11:34 UTC, Shwetabhk commented
Get Response of API `GET api/workspaces/2/mappings/employee/`
```
{
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
        {
            "id": 1,
            "source_employee": {
                "attribute_type": "CATEGORY",
                "display_name": "Category",
                "value": "00",
                "source_id": "110351",
                "auto_mapped": false,
                "auto_created": false,
                "active": null,
                "detail": null,
                "created_at": "2021-04-12T14:53:34.572984Z",
                "updated_at": "2021-04-12T14:53:34.573030Z",
                "workspace": 4
            },
            "destination_employee": {
                "attribute_type": "CUSTOMER",
                "display_name": "customer",
                "value": "Ashwinnnnnn",
                "destination_id": "103",
                "auto_created": false,
                "active": null,
                "detail": null,
                "created_at": "2021-04-13T10:19:48.710815Z",
                "updated_at": "2021-04-13T10:19:48.710878Z",
                "workspace": 1
            },
            "destination_vendor": {
                "attribute_type": "CUSTOMER",
                "display_name": "customer",
                "value": "Ashwinnnnnn",
                "destination_id": "103",
                "auto_created": false,
                "active": null,
                "detail": null,
                "created_at": "2021-04-13T10:19:48.710815Z",
                "updated_at": "2021-04-13T10:19:48.710878Z",
                "workspace": 1
            },
            "destination_card_account": {
                "attribute_type": "CUSTOMER",
                "display_name": "customer",
                "value": "Ashwinnnnnn",
                "destination_id": "103",
                "auto_created": false,
                "active": null,
                "detail": null,
                "created_at": "2021-04-13T10:19:48.710815Z",
                "updated_at": "2021-04-13T10:19:48.710878Z",
                "workspace": 1
            },
            "created_at": "2021-07-23T09:54:10.252670Z",
            "updated_at": "2021-07-23T09:54:10.252913Z",
            "workspace": 2
        }
    ]
}
```

2021-07-23 11:36 UTC, Shwetabhk commented
@ashwin1111 You can carry it forward from here

2021-07-26 07:33 UTC, ashwin1111 commented on fyle_accounting_mappings/views.py
> +    permission_classes = []
TODO: remove

2021-07-27 15:39 UTC, ashwin1111 requested changes

2021-07-27 15:39 UTC, ashwin1111 commented on fyle_accounting_mappings/models.py
> +        return employee_mapping
return employee_mapping, _
```suggestion
        return employee_mapping, _
```

2021-07-27 15:39 UTC, ashwin1111 commented on fyle_accounting_mappings/serializers.py
> +        if destination_employee and 'id' in destination_employee:
```suggestion
        if destination_employee and 'id' in destination_employee and destination_employee['id']:
```

2021-07-27 15:39 UTC, ashwin1111 commented on fyle_accounting_mappings/serializers.py
> +        if destination_vendor and 'id' in destination_vendor:
```suggestion
        if destination_vendor and 'id' in destination_vendor and destination_vendor['id']:
```

2021-07-27 15:39 UTC, ashwin1111 commented on fyle_accounting_mappings/serializers.py
> +        if destination_card_account and 'id' in destination_card_account:
```suggestion
        if destination_card_account and 'id' in destination_card_account and destination_card_account['id']:
```

2021-07-28 07:20 UTC, merged