get only active category mappings
fylein/fyle-accounting-mappings pull request #70
Opened 2022-12-09 13:22 UTC by harshithaputtaswamy

2022-12-12 13:26 UTC, NileshPant1999 commented on fyle_accounting_mappings/views.py
> +            workspace_id=self.kwargs['workspace_id'], source_category__active=True
please update the version too before merging

2022-12-12 13:26 UTC, NileshPant1999 approved these changes

2022-12-13 13:36 UTC, ashwin1111 approved these changes

2022-12-13 14:20 UTC, ashwin1111 requested changes

2022-12-13 14:20 UTC, ashwin1111 commented on fyle_accounting_mappings/views.py
> -            workspace_id=self.kwargs['workspace_id']
conditional filter via query params

2022-12-14 14:07 UTC, ashwin1111 approved these changes

2022-12-14 14:26 UTC, merged